"""create trips table

Revision ID: 7945d8dc809f
Revises: 
Create Date: 2026-06-05 13:40:50.167518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7945d8dc809f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_created_at'), 'trip', ['created_at'], unique=False)
    op.create_index(op.f('ix_trip_name'), 'trip', ['name'], unique=False)
    op.create_index(op.f('ix_trip_owner_id'), 'trip', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trip_owner_id'), table_name='trip')
    op.drop_index(op.f('ix_trip_name'), table_name='trip')
    op.drop_index(op.f('ix_trip_created_at'), table_name='trip')
    op.drop_table('trip')
    # ### end Alembic commands ###
